USE automated_sales_reporting;


#1. The sales manager wants a temporary table containing the total sales generated by each salesperson.
 #  Create the temporary table and return the salesperson and their total sales.
 
 CREATE TEMPORARY  TABLE  total_sales_table
 SELECT salesperson,SUM(amount) AS total_sales
 FROM sales
 GROUP BY salesperson
;
SELECT*
FROM total_sales_table;

#2. Create a temporary table containing the total sales for each product category. Return the category and total sales.

CREATE TEMPORARY TABLE category_total_sales
SELECT category,SUM(amount) AS total_sales
FROM sales
GROUP BY category;

SELECT*
FROM category_total_sales;

#3. Create a temporary table containing the number of sales made by each salesperson.
# Return the salesperson and number of sales


CREATE TEMPORARY TABLE temp
SELECT salesperson,COUNT(*) AS number_of_sales
FROM sales
GROUP BY salesperson;

SELECT*
FROM temp;

#4. Create a temporary table containing sales where the amount is greater than R5,000.
# Return the sale ID, salesperson, product and amount

CREATE TEMPORARY TABLE salesOver5k
SELECT sale_id,salesperson,product,amount
FROM sales
WHERE amount > 5000;

SELECT*
FROM salesOver5k;

#5. Create a temporary table containing each salesperson's average sale amount.
# Return the salesperson and average sale amount

CREATE TEMPORARY TABLE salesAverage AS
SELECT salesperson,AVG(amount) AS average_sale_amount
FROM sales
GROUP BY salesperson;

SELECT*
FROM salesAverage;

#6. Create a temporary table containing the monthly sales totals. Return the month and total sales.

CREATE TEMPORARY TABLE monthlySales
SELECT SUBSTRING(sale_date,6,2) AS "month",SUM(amount) AS total_sales
FROM sales
GROUP BY month;

SELECT*
FROM monthlySales;

#7. The manager wants to identify salespeople whose total sales are greater than R15,000. 
#Create a temporary table containing salesperson totals, then return only salespeople above R15,000.

CREATE TEMPORARY TABLE sales_over_15k
SELECT salesperson,SUM(amount) sales_total
FROM sales
GROUP BY salesperson
HAVING sales_total > 15000 ;

SELECT*
FROM sales_over_15k;

#8. Create a temporary table containing total sales by salesperson and category.
# Return the salesperson, category and total sales.

CREATE TEMPORARY TABLE sales_temp_table
SELECT salesperson,category,SUM(amount) total_sales
FROM sales
GROUP BY salesperson,category;

SELECT*
FROM sales_temp_table;


#9. Create a temporary table containing each salesperson's highest individual sale.
# Return the salesperson and highest sale.

CREATE TEMPORARY TABLE high_sale
SELECT salesperson,MAX(amount) AS highest_sale
FROM sales
GROUP BY salesperson;

SELECT*
FROM high_sale;

#10. Create a temporary table containing the top 3 salespeople based on total sales.
# Return the salesperson, total sales and rank/order.

CREATE TEMPORARY TABLE top_3_sales
SELECT salesperson,SUM(amount) AS total_sales, RANK()OVER(ORDER BY SUM(amount)DESC) as ranking
FROM sales
GROUP BY salesperson
LIMIT 3
;

SELECT*
FROM top_3_sales;




