USE automated_sales_reporting;


#1. The sales manager wants a stored procedure that returns all sales made by a specific salesperson.
#Create a procedure that accepts the salesperson's name as an input parameter and returns their sale_id, product, amount, and sale_date.

DELIMITER $$
CREATE PROCEDURE salesperson_details (IN p_salesperson VARCHAR(50))
BEGIN
SELECT sale_id,product,amount,sale_date
FROM sales
WHERE salesperson = p_salesperson;
END $$

CALL salesperson_details('John');

#2. Create a stored procedure that accepts a product category as an input parameter and returns all sales belonging to that category.
# Return:sale_id,salesperson,product,amount

DELIMITER $$
CREATE PROCEDURE category_sales(IN p_category VARCHAR(50))
BEGIN
SELECT sale_id,salesperson,product,amount
FROM sales
WHERE category = p_category;
END $$

CALL category_sales("Electronics");

#3. The manager wants to quickly check how much a particular salesperson generated in total sales.
# Create a stored procedure that accepts a salesperson's name and returns:salesperson,total sales

DELIMITER $$
CREATE PROCEDURE saleperson_total_sales(IN p_salesperson VARCHAR(50))
BEGIN
SELECT salesperson,SUM(amount) AS total_sales
FROM sales
WHERE salesperson = p_salesperson
GROUP BY salesperson;
END $$

CALL saleperson_total_sales('Lerato');


#4. Create a stored procedure that accepts a minimum sales amount and returns all sales where the amount is greater than that value.
# Return: sale_id, salesperson, product,amount

DELIMITER $$
CREATE PROCEDURE salesGreater(IN p_amount DECIMAL(10,2))
BEGIN
SELECT sale_id, salesperson, product,amount
FROM sales
WHERE amount > p_amount
;
END $$

CALL salesGreater(2500);


#5 Create a stored procedure that accepts a salesperson's name and returns their average sale amount.
# Return:salesperson ,average sale amount

DELIMITER $$
CREATE PROCEDURE average_sales(IN p_salesperson VARCHAR(50))
BEGIN
SELECT salesperson,AVG(amount) average_sale_amount
FROM sales
WHERE salesperson = p_salesperson
GROUP BY salesperson
;
END $$

CALL average_sales('Sarah');


#6. The manager wants to check how many sales a particular salesperson has made.
#Create a stored procedure that accepts a salesperson's name and returns:salesperson ,number of sales

DELIMITER $$
CREATE PROCEDURE count_sales (IN p_salesperson VARCHAR(50))
BEGIN
SELECT salesperson,COUNT(*)AS number_of_sales
FROM sales
WHERE salesperson = p_salesperson
GROUP BY salesperson;
END $$

CALL count_sales("Lerato");

#7. Create a stored procedure that accepts a category and returns the total sales generated by that category.
# Return: category ,total sales
DROP PROCEDURE IF EXISTS categoryTotalSales;

DELIMITER $$
 CREATE PROCEDURE  categoryTotalSales(IN p_category VARCHAR(50))
BEGIN
SELECT category ,SUM(amount) AS total_sales
FROM sales
WHERE category = p_category
GROUP BY category;
END $$

CALL categoryTotalSales("Accessories");

#8. The manager wants to find the highest individual sale made by a particular salesperson.
# Create a stored procedure that accepts a salesperson's name and returns: salesperson ,highest sale

DELIMITER $$
CREATE PROCEDURE highest_sale(IN p_salesperson VARCHAR(50))
BEGIN
SELECT salesperson,MAX(amount) highest_sale
FROM sales
WHERE salesperson =p_salesperson
GROUP BY salesperson;
END $$

CALL highest_sale ("Sarah");

#9. Create a stored procedure that accepts a salesperson's name and returns their sales ordered from highest amount to lowest amount.
#Return: sale_id, product ,amount ,sale_date

DELIMITER $$
CREATE PROCEDURE sales_ordering(p_salesperson VARCHAR(50))
BEGIN
SELECT sale_id,product,amount,sale_date
FROM sales
WHERE salesperson = p_salesperson
ORDER BY amount DESC;
END $$

CALL sales_ordering ("Thabo");


#10. The manager wants a procedure that accepts a salesperson's name and returns a summary of their performance.
# Return:salesperson,total sales ,average sale amount ,number of sales,highest individual sale


DELIMITER $$
CREATE PROCEDURE salesperson_performance (p_salesperson VARCHAR(50))
BEGIN
SELECT salesperson,SUM(amount) total_sales,AVG(amount)average_sale_amount,COUNT(*) number_of_sales,MAX(amount) highest_sale
FROM sales
WHERE salesperson =p_salesperson
GROUP BY salesperson;
END $$

CALL salesperson_performance("Lerato");
















